version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    restart: always
    ports:
      - "4306:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - TZ=America/Santiago
      - MYSQL_ROOT_PASSWORD=db
      - MYSQL_DATABASE=tarea3
    volumes:
      -  ./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080