services:
  mysql:
    image: mysql:9.3.0-oraclelinux9
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - TZ=America/Santiago
      - MYSQL_ROOT_PASSWORD=Star@24*
      - MYSQL_DATABASE=productdb2
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer:4.8.1  # versión fija
    restart: always
    ports:
      - "8090:8080"